version: '3.9'

services:
  mysql:
    image: 'mysql:8.4.0'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${DB_DATABASE:?}"
      MYSQL_USER: "${DB_USER:?}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?}"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "${DB_PORT:?}:3306"